// Badge update — debounced to avoid hammering cookies API on rapid tab switches
const _badgeTimers = new Map()
function scheduleBadge(tabId) {
  clearTimeout(_badgeTimers.get(tabId))
  _badgeTimers.set(tabId, setTimeout(() => { _badgeTimers.delete(tabId); updateBadge(tabId) }, 120))
}

chrome.tabs.onActivated.addListener(({ tabId }) => scheduleBadge(tabId))
chrome.tabs.onUpdated.addListener((tabId, info) => {
  if (info.status === 'complete') scheduleBadge(tabId)
})

async function updateBadge(tabId) {
  try {
    const tab = await chrome.tabs.get(tabId)
    if (!tab?.url || tab.url.startsWith('chrome://') || tab.url.startsWith('edge://') || tab.url.startsWith('about:')) {
      chrome.action.setBadgeText({ text: '', tabId }); return
    }
    const url     = new URL(tab.url)
    const cookies = await chrome.cookies.getAll({ domain: url.hostname })
    // The badge only fits ~4 glyphs; big cookie jars would render as mush.
    const text = cookies.length === 0 ? '' : cookies.length > 99 ? '99+' : String(cookies.length)
    chrome.action.setBadgeText({ text, tabId })
    chrome.action.setBadgeBackgroundColor({ color: '#2563eb', tabId })
  } catch { /* tab closed or navigated away */ }
}

// Context menu — removeAll first to prevent duplicate-ID error on reload/update.
// The title comes from _locales via chrome.i18n so it follows the browser's UI
// language; the popup's own language picker cannot reach a service worker.
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id: 'export-cookies',
      title: chrome.i18n.getMessage('ctxExport') || 'Export cookies for this site — CookieXport',
      contexts: ['page', 'frame'],
    })
  })
})

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId !== 'export-cookies' || !tab?.url) return
  try {
    const url     = new URL(tab.url)
    const domain  = url.hostname
    const cookies = await chrome.cookies.getAll({ domain })
    if (!cookies.length) return

    const content  = buildNetscape(cookies)
    const clean    = domain.replace(/[^a-z0-9.-]/gi, '_')
    const filename = `cookies_${clean}.txt`
    // data: URL avoids Blob+createObjectURL which is unavailable in MV3 service workers
    const dataUrl  = 'data:text/plain;charset=utf-8,' + encodeURIComponent(content)
    chrome.downloads.download({ url: dataUrl, filename, saveAs: false })
  } catch (e) {
    console.error('CookieXport context menu error:', e)
  }
})

function buildNetscape(cookies) {
  const lines = ['# Netscape HTTP Cookie File', `# Generated by CookieXport — ${new Date().toISOString()}`, '']
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`
    const sub    = c.domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0
    lines.push([domain, sub, c.path || '/', secure, expiry, c.name, c.value].join('\t'))
  }
  return lines.join('\n')
}
