/* Cookie names and values are arbitrary site-controlled strings that end up
   inside quoted literals in the snippets below. Each target language needs its
   own escaping — a JWT ending in "==" or a value with a quote in it must not
   break (or change the meaning of) the generated code.
   Named Quote, not esc: popup.js already owns the global `esc`. */
const Quote = {
  // Inside a double-quoted POSIX shell string
  sh: s => String(s).replace(/[\\"$`]/g, m => '\\' + m),
  // Inside a double-quoted PHP string — `$` interpolates variables there
  php: s => String(s).replace(/[\\"$]/g, m => '\\' + m),
  // JSON string literal — also valid for JS, Python and Go source
  str: s => JSON.stringify(String(s)),
}

/* Cookie files carry expiry as unix seconds (our own JSON export,
   EditThisCookie), unix milliseconds, or an ISO date. `new Date(number)` reads
   milliseconds, so a raw seconds value would land in 1970 — sniff the scale. */
function toEpochSeconds(v) {
  if (v === undefined || v === null || v === '') return undefined
  const num = typeof v === 'number' ? v : Number(String(v).trim())
  if (Number.isFinite(num)) {
    if (num <= 0) return undefined
    return Math.floor(num > 1e11 ? num / 1000 : num)
  }
  const ms = Date.parse(v)
  return Number.isNaN(ms) ? undefined : Math.floor(ms / 1000)
}

const Formatter = {
  /* ── Netscape HTTP Cookie File ──────────────────────────── */
  netscape(cookies) {
    const lines = [
      '# Netscape HTTP Cookie File',
      `# Generated by CookieXport — ${new Date().toISOString()}`,
      '',
    ]
    for (const c of cookies) {
      const domain    = c.domain.startsWith('.') ? c.domain : `.${c.domain}`
      const subdomain = c.domain.startsWith('.') ? 'TRUE' : 'FALSE'
      const secure    = c.secure ? 'TRUE' : 'FALSE'
      const expiry    = c.expirationDate ? Math.floor(c.expirationDate) : 0
      lines.push([domain, subdomain, c.path || '/', secure, expiry, c.name, c.value].join('\t'))
    }
    return lines.join('\n')
  },

  /* ── JSON ───────────────────────────────────────────────── */
  json(cookies) {
    return JSON.stringify(cookies.map(c => ({
      name: c.name, value: c.value, domain: c.domain, path: c.path,
      expires: c.expirationDate ? Math.floor(c.expirationDate) : null,
      expiresISO: c.expirationDate ? new Date(c.expirationDate * 1000).toISOString() : null,
      secure: c.secure, httpOnly: c.httpOnly, sameSite: c.sameSite, session: !c.expirationDate,
    })), null, 2)
  },

  /* ── cURL ───────────────────────────────────────────────── */
  curl(cookies) {
    if (!cookies.length) return ''
    // Values go out exactly as the browser stores them. Percent-encoding here
    // would rewrite the "=" padding on every base64 / JWT cookie and the
    // server would reject the session.
    const pairs = cookies.map(c => `${c.name}=${c.value}`).join('; ')
    return `curl -H "Cookie: ${Quote.sh(pairs)}" "<URL>"`
  },

  /* ── Header string ──────────────────────────────────────── */
  header(cookies) {
    return cookies.map(c => `${c.name}=${c.value}`).join('; ')
  },

  /* ── Python requests ────────────────────────────────────── */
  python(cookies) {
    const pairs = cookies.map(c => `    ${Quote.str(c.name)}: ${Quote.str(c.value)}`).join(',\n')
    return `import requests\n\nsession = requests.Session()\nsession.cookies.update({\n${pairs}\n})\n\nresponse = session.get("<URL>")\nprint(response.text)`
  },

  /* ── Node.js fetch / axios ──────────────────────────────── */
  node(cookies) {
    const cookieStr = Quote.str(cookies.map(c => `${c.name}=${c.value}`).join('; '))
    return `// fetch\nconst response = await fetch("<URL>", {\n  headers: { "Cookie": ${cookieStr} }\n})\n\n// axios\nconst { data } = await axios.get("<URL>", {\n  headers: { "Cookie": ${cookieStr} }\n})`
  },

  /* ── Playwright ─────────────────────────────────────────── */
  playwright(cookies) {
    const arr = cookies.map(c => ({
      name: c.name, value: c.value, domain: c.domain, path: c.path || '/',
      expires: c.expirationDate || -1, httpOnly: c.httpOnly, secure: c.secure,
      sameSite: ['Strict', 'Lax', 'None'].includes(c.sameSite) ? c.sameSite : 'None',
    }))
    return `const { chromium } = require('playwright')\n\nconst browser = await chromium.launch()\nconst context = await browser.newContext()\n\nawait context.addCookies(${JSON.stringify(arr, null, 2)})\n\nconst page = await context.newPage()\nawait page.goto("<URL>")`
  },

  /* ── Puppeteer ──────────────────────────────────────────── */
  puppeteer(cookies) {
    const arr = cookies.map(c => ({
      name: c.name, value: c.value, domain: c.domain, path: c.path || '/',
      ...(c.expirationDate ? { expires: Math.floor(c.expirationDate) } : {}),
      httpOnly: c.httpOnly, secure: c.secure,
    }))
    const lines = arr.map(c => '  ' + JSON.stringify(c)).join(',\n')
    return `const puppeteer = require('puppeteer')\n\nconst browser = await puppeteer.launch()\nconst page = await browser.newPage()\n\nawait page.setCookie(\n${lines}\n)\n\nawait page.goto("<URL>")`
  },

  /* ── Selenium (Python) ──────────────────────────────────── */
  selenium(cookies) {
    const domain = cookies[0]?.domain?.replace(/^\./, '') || 'example.com'
    const lines = cookies.map(c =>
      `driver.add_cookie({"name": ${Quote.str(c.name)}, "value": ${Quote.str(c.value)}, "domain": ${Quote.str(c.domain)}, "path": ${Quote.str(c.path || '/')}, "secure": ${c.secure ? 'True' : 'False'}})`
    ).join('\n')
    return `from selenium import webdriver\nfrom selenium.webdriver.chrome.options import Options\n\ndriver = webdriver.Chrome()\ndriver.get("https://${domain}")  # Navigate to domain first\n\n${lines}\n\ndriver.get("<URL>")`
  },

  /* ── PHP cURL ───────────────────────────────────────────── */
  php(cookies) {
    const cookieStr = Quote.php(cookies.map(c => `${c.name}=${c.value}`).join('; '))
    return `<?php\n$ch = curl_init();\n$url = "<URL>";\n$cookies = "${cookieStr}";\n\ncurl_setopt_array($ch, [\n    CURLOPT_URL            => $url,\n    CURLOPT_COOKIE         => $cookies,\n    CURLOPT_RETURNTRANSFER => true,\n    CURLOPT_FOLLOWLOCATION => true,\n    CURLOPT_SSL_VERIFYPEER => false,\n]);\n\n$response = curl_exec($ch);\ncurl_close($ch);\necho $response;`
  },

  /* ── Go net/http ────────────────────────────────────────── */
  go(cookies) {
    const lines = cookies.map(c => `\treq.AddCookie(&http.Cookie{Name: ${Quote.str(c.name)}, Value: ${Quote.str(c.value)}})`).join('\n')
    return `package main\n\nimport (\n\t"fmt"\n\t"io"\n\t"net/http"\n)\n\nfunc main() {\n\tclient := &http.Client{}\n\treq, _ := http.NewRequest("GET", "<URL>", nil)\n\n${lines}\n\n\tresp, err := client.Do(req)\n\tif err != nil { panic(err) }\n\tdefer resp.Body.Close()\n\tbody, _ := io.ReadAll(resp.Body)\n\tfmt.Println(string(body))\n}`
  },

  /* ── HAR (HTTP Archive) ─────────────────────────────────── */
  har(cookies) {
    // HAR 1.2 marks most of these fields required. A stripped-down entry loads
    // in some viewers and is rejected outright by others, so emit the full shape.
    const domain = cookies[0]?.domain?.replace(/^\./, '') || 'example.com'
    const entry = {
      startedDateTime: new Date().toISOString(),
      time: 0,
      request: {
        method: 'GET',
        url: `https://${domain}/`,
        httpVersion: 'HTTP/1.1',
        cookies: cookies.map(c => ({
          name: c.name, value: c.value, path: c.path || '/', domain: c.domain,
          expires: c.expirationDate ? new Date(c.expirationDate * 1000).toISOString() : null,
          httpOnly: !!c.httpOnly, secure: !!c.secure,
        })),
        headers: [{ name: 'Cookie', value: cookies.map(c => `${c.name}=${c.value}`).join('; ') }],
        queryString: [],
        headersSize: -1,
        bodySize: -1,
      },
      response: {
        status: 0, statusText: '', httpVersion: 'HTTP/1.1',
        cookies: [], headers: [],
        content: { size: 0, mimeType: 'x-unknown' },
        redirectURL: '', headersSize: -1, bodySize: -1,
      },
      cache: {},
      timings: { send: 0, wait: 0, receive: 0 },
    }
    return JSON.stringify({
      log: {
        version: '1.2',
        // Read from the manifest so the HAR creator block never drifts on a bump
        creator: { name: 'CookieXport', version: globalThis.chrome?.runtime?.getManifest?.().version ?? '1.0' },
        pages: [], entries: [entry],
      },
    }, null, 2)
  },

  /* ── Base64 ─────────────────────────────────────────────── */
  base64(cookies) {
    const json  = this.json(cookies)
    const bytes = new TextEncoder().encode(json)
    let bin = ''
    bytes.forEach(b => bin += String.fromCharCode(b))
    return btoa(bin)
  },

  /* ── Custom template ────────────────────────────────────── */
  custom(cookies, template) {
    if (!template) return this.header(cookies)
    return cookies.map(c =>
      template
        .replace(/\{\{name\}\}/g, c.name)
        .replace(/\{\{value\}\}/g, c.value)
        .replace(/\{\{domain\}\}/g, c.domain)
        .replace(/\{\{path\}\}/g, c.path || '/')
        .replace(/\{\{expires\}\}/g, c.expirationDate ? Math.floor(c.expirationDate) : '0')
        .replace(/\{\{expiresISO\}\}/g, c.expirationDate ? new Date(c.expirationDate * 1000).toISOString() : '')
        .replace(/\{\{secure\}\}/g, c.secure ? 'true' : 'false')
        .replace(/\{\{httpOnly\}\}/g, c.httpOnly ? 'true' : 'false')
    ).join('\n')
  },

  /* ── Dispatch ───────────────────────────────────────────── */
  format(cookies, fmt, customTemplate) {
    switch (fmt) {
      case 'netscape':   return { content: this.netscape(cookies),          ext: 'txt',  mime: 'text/plain' }
      case 'json':       return { content: this.json(cookies),              ext: 'json', mime: 'application/json' }
      case 'curl':       return { content: this.curl(cookies),              ext: 'sh',   mime: 'text/plain' }
      case 'header':     return { content: this.header(cookies),            ext: 'txt',  mime: 'text/plain' }
      case 'python':     return { content: this.python(cookies),            ext: 'py',   mime: 'text/plain' }
      case 'node':       return { content: this.node(cookies),              ext: 'js',   mime: 'text/plain' }
      case 'playwright': return { content: this.playwright(cookies),        ext: 'js',   mime: 'text/plain' }
      case 'puppeteer':  return { content: this.puppeteer(cookies),         ext: 'js',   mime: 'text/plain' }
      case 'selenium':   return { content: this.selenium(cookies),          ext: 'py',   mime: 'text/plain' }
      case 'php':        return { content: this.php(cookies),               ext: 'php',  mime: 'text/plain' }
      case 'go':         return { content: this.go(cookies),                ext: 'go',   mime: 'text/plain' }
      case 'har':        return { content: this.har(cookies),               ext: 'json', mime: 'application/json' }
      case 'base64':     return { content: this.base64(cookies),            ext: 'txt',  mime: 'text/plain' }
      case 'custom':     return { content: this.custom(cookies, customTemplate), ext: 'txt', mime: 'text/plain' }
      default:           return { content: this.netscape(cookies),          ext: 'txt',  mime: 'text/plain' }
    }
  },

  /* ── Parse imported cookies ─────────────────────────────── */
  parse(text) {
    text = text.trim()

    // JSON — a bare array, a HAR log, or a { cookies: [...] } wrapper
    if (text.startsWith('[') || text.startsWith('{')) {
      try {
        const parsed = JSON.parse(text)
        const arr = Array.isArray(parsed)
          ? parsed
          : parsed.cookies || parsed.log?.entries?.[0]?.request?.cookies || []
        if (!Array.isArray(arr)) return null
        return arr.filter(c => c && c.name && c.value !== undefined).map(c => ({
          name: c.name, value: String(c.value),
          domain: c.domain || '', path: c.path || '/',
          expirationDate: toEpochSeconds(c.expirationDate ?? c.expires ?? c.expiresDate ?? c.expiry),
          secure: !!c.secure, httpOnly: !!c.httpOnly,
        }))
      } catch { return null }
    }

    // Netscape format
    const cookies = []
    for (const raw of text.split(/\r?\n/)) {
      let line = raw.trim()
      if (!line) continue

      // curl and yt-dlp mark httpOnly cookies with a "#HttpOnly_" domain prefix.
      // It looks like a comment, so unwrap it before the comment check drops it.
      let httpOnly = false
      if (line.startsWith('#HttpOnly_')) {
        httpOnly = true
        line = line.slice('#HttpOnly_'.length)
      } else if (line.startsWith('#')) {
        continue
      }

      const parts = line.split('\t')
      if (parts.length < 7) continue
      const [domain, , path, secure, expiry, name, ...rest] = parts
      cookies.push({
        domain, path, name,
        // A value may legally contain tabs; everything after field 7 belongs to it.
        value: rest.join('\t'),
        secure: secure === 'TRUE',
        httpOnly,
        expirationDate: toEpochSeconds(expiry),
      })
    }
    return cookies.length ? cookies : null
  },
}
